version: '3.8'

services:
  db:
    container_name: pg_db
    image: postgres:16
    restart: always
    ports:
      - "${DB_PORT}:${DB_PORT}"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    env_file:
      - ./.env

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    restart: unless-stopped
    ports:
      - "5050:80"
    depends_on:
      - db
    environment:
      - PGADMIN_DEFAULT_EMAIL=${POSTGRES_USER}@${POSTGRES_USER}.com
      - PGADMIN_DEFAULT_PASSWORD=${POSTGRES_PASSWORD}

  todo-backend:
    container_name: backend
    build:
      context: .
      dockerfile: ./backend/DockerFile
    ports:
      - "${SERVER_PORT}:${SERVER_PORT}"
      - "${SOCKET_PORT}:${SOCKET_PORT}"
    depends_on:
      - db
      - todo-frontend
    volumes:
      - ./backend:/app
      - todo-backend_node-modules:/app/node_modules
    env_file:
      - ./backend/.env

  todo-frontend:
    container_name: frontend
    build:
      context: .
      dockerfile: ./frontend/DockerFile
    ports:
      - "5173:5173"
    env_file:
      - ./frontend/.env

  frontend-nginx:
    image: nginx:latest
    container_name: frontend-nginx
    ports:
      - "${NGINX_SERVER_PORT}:80"
    depends_on:
      - todo-frontend
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    env_file:
      - ./.env

  backend-nginx:
    image: nginx:latest
    container_name: backend-nginx
    restart: always
    ports:
      - "${NGINX_SOCKET_PORT}:80"
    depends_on:
      - todo-backend
    volumes:
      - ./nginx/nginxbe.conf:/etc/nginx/templates/default.conf.template
    env_file:
      - ./.env

volumes:
  postgres-data:
  todo-backend_node-modules: